function [Time,Elevator,Pitchangle,Speed,Altitude] = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [Time,Elevator,Pitchangle,Speed,Altitude] = IMPORTFILE(FILE) reads data
%   from the first worksheet in the Microsoft Excel spreadsheet file named
%   FILE and returns the data as column vectors.
%
%   [Time,Elevator,Pitchangle,Speed,Altitude] = IMPORTFILE(FILE,SHEET)
%   reads from the specified worksheet.
%
%   [Time,Elevator,Pitchangle,Speed,Altitude] =
%   IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [Time,Elevator,Pitchangle,Speed,Altitude] = importfile('Phugoid_GpA.xls','Sheet1',2,1744);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2016/10/06 10:05:47

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 1744;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('A%d:E%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('A%d:E%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
Time = data(:,1);
Elevator = data(:,2);
Pitchangle = data(:,3);
Speed = data(:,4);
Altitude = data(:,5);


